function makeInputFiles(obj)
%MAKEINPUTFILES Create Input Files
%   Detailed explanation goes here
    
    % Prepare coolprop
    cp = CoolPropWrapper.CoolPropWrapper('Water');
    cp.outputMode = 'vec';
  
    % Make caseFolder
    obj.makeCaseFolder('+Groeneveld');
    caseFolder = obj.caseFolderPaths.inputs;
    
    % Retrieve entry with entryID
    entry = obj.dataset(obj.dataset.Number == obj.entryID,:);

    % TODO: check entry size, error if more than 1 is found
    % ...

    % Flow area
    flowArea = 0.25*pi.*entry.TubeDiameter.^2;
    heatedArea = pi.*entry.TubeDiameter.*entry.HeatedLength;

    % Geometry file
    obj.geometryID = string(entry.GeometryID);
    Inputs.Geometry.writeInputFile( ...
        obj.geometryFilePath, ...
        obj.geometryID, ...
        "LENGTH", entry.HeatedLength, ...
        "AREA",   flowArea, ...
        "PERIM",  entry.TubeDiameter ...
        );            
    
    % Model file
    obj.modelID = string(obj.entryID);
    Inputs.Model.writeInputFile( ...
        obj.modelFilePath, ...
        obj.modelID, ...
        "NNODES", 100, ...
        "FLUID", "WATER", ...
        "PROPERTIES", "SATURATED","MOMENTFILM",'algebraic');

    % Boundary conditions file
    pressure = entry.Pressure .* 1000;  % kPa -> Pa
    mflow = entry.MassFlux .* flowArea;
    power = entry.CHF * 1000 .* heatedArea;           % kW/m^2 -> W
    for timeStep = [0 3]
        Inputs.BoundaryConditions.writeInputFile( ...
            obj.bcFilePath, ...
            timeStep, ...
            pressure, ...       
            cp.enthalpy( ...
                'P',pressure, ...
                'T', celcius2kelvin(entry.InletTemperature)), ...
            mflow, ...
            "POWER", power, ...  
            "WMESH", entry.HeatedLength/2.*[1 1], ...
            "WPOWER", [1 1] ...
            );
    end    

    % Options file
    obj.optionsID = "STEADY";
    Inputs.Options.writeInputFile( ...
        obj.optionsFilePath, ...
        obj.optionsID);
    
    %% HELPER FUNCTIONS
    
    % Celcius to Kelvin
    function k = celcius2kelvin(c)
        k = c+273.15;
    end
end

