function makeInputFiles(adam)
%MAKEINPUTFILES Create Input Files
%   Detailed explanation goes here
    
    % Prepare coolprop
    cp = CoolPropWrapper.CoolPropWrapper('Water');
    cp.outputMode = 'vec';
  
    % Make caseFolder
    adam.makeCaseFolder('+Adamsson2006');
    caseFolder = adam.caseFolderPaths.inputs;
    
    % Retrieve entry with entryID
    entry = adam.dataset(strcmp(adam.dataset.TestID, adam.entryID),:);

    % Retrieve heating type, wmesh, wpower
    heatType = regexp(adam.entryID,'(\w+)_M','tokens');
    heatType = heatType{1}{1};
    wmesh = adam.misc.wpowerLUT.WMESH;
    wpower = adam.misc.wpowerLUT.(heatType);

    % TODO: check entry size, error if more than 1 is found
    % ...

    % Flow area
    diam=14E-3;                                                             % [m]
    perim=pi*diam;                                                          % [m]
    flowArea=pi*diam^2/4;                                                   % [m2]
    
    % Geometry file
    adam.geometryID = 'HWATFILM';
    Inputs.Geometry.writeInputFile( ...
        adam.geometryFilePath, ...
        adam.geometryID, ...
        "LENGTH", 3.65, ...
        "AREA",   flowArea, ...
        "PERIM",  perim ...
        );            
    
    % Model file
    adam.modelID = 'HWATS';
    Inputs.Model.writeInputFile( ...
        adam.modelFilePath, ...
        adam.modelID , ...
        "NNODES",       100, ...
        "FLUID",        "WATER", ...
        "PROPERTIES",   "SATURATED", ...
        "FRICTION",     [0.2 -0.2 0.0], ...
        "TPFM",         "SLIP", ...
        "TPKM",         "HOMOGENEOUS", ...
        "VOID",         "SLIP",...
        "OAFDROPRATIO", 0.5, ...
        "OAF",          "WALLIS_SIMP" ...
        );

    % Boundary conditions file
    P = entry.Pressure*1E6;                                                 % [Pa]
    hf = cp.enthalpy('P',P,'Q',0);                                          % [J/kg]
    hg = cp.enthalpy('P',P,'Q',1);                                          % [J/kg]
    tin = cp.temperature('P',P,'Q',0)-entry.Subcooling;                     % [K]
    hin = cp.enthalpy('P',P,'T',tin);                                       % [J/kg]
    hout = entry.Quality.*(hg-hf)+hf;                                       % [J/kg]
    M = entry.MassFlux.*flowArea;                                           % [kg/s]
    power = (hout-hin).*M;                                                  % [W]
    elev=[0 cumsum(wmesh).'];                                               % [m]
    rpowdist=[0 cumsum(wpower).']./sum(wpower);                             % [-] Relative power distribution

    h = hin+rpowdist.*power./M;                                             % [J/kg]
    x = (h-hf)./(hg-hf);                                                    % [-]
    steamflow = max(0,x.*M);                                                % [kg/s]
    steamflow = interp1(elev,steamflow,entry.Elevation{1},'linear');

    for timeStep = 0
        Inputs.BoundaryConditions.writeInputFile( ...
            adam.bcFilePath, ...
            timeStep, ...
            P, ...       
            hin, ...
            M, ...
            "POWER", power, ...  
            "WMESH", wmesh, ...
            "WPOWER", wpower, ...
            "TIN", tin, ...
            "HOUT", hout, ...
            "XOUT", entry.Quality, ...
            "ELEV", entry.Elevation{1}, ...
            "STEAMFLOW", steamflow, ...
            "FILMFLOW", entry.FilmFlow{1}./60, ...
            "DROPFLOW", M-entry.FilmFlow{1}./60-steamflow ...
            );
        
    end    

    % Options file
    adam.optionsID = "STEADY";
    Inputs.Options.writeInputFile( ...
        adam.optionsFilePath, ...
        adam.optionsID, ...
        "TSTEP",        0.1, ...
        "MAXITER",      100, ...
        "ERRORW",       1E-3, ...
        "ERRORP",       1E1, ...
        "ERRORH",       1E0, ...
        "SSMAXITER",    100, ...
        "SSCONVW",      2E-4, ...
        "SSCONVP",      1E-4, ...
        "SSCONVH",      1E-4 ...
        );
    

end

